### PR TITLE
Weak assignments

### PR DESCRIPTION
**Pull request by elwhitman**
added tests for weak assignments and their edge cases, also included tests from assignment description, and edge case of single ill formed statement where lexer reaches EOF while parsing

### CODE REVIEW

**Comment by daveho** [comment]
These are great, thank you!  There are just two issues:

contrib08 - exponents used are very large; I will change it to not
  overflow range of 64 bit signed integers

contrib10 - weak assignments may not be used in subexpressions,
  so I will omit this test

Will be merging shortly.

**Comment by elwhitman** [comment]
Ok, I was wondering about weak assignments as sub expressions, and the extra code to accommodate them is significant. The description doesn’t say anything about why they are invalid. Shouldn’t they behave the same way as assignments? Don’t weak assignments just returns the value assigned?

**Comment by elwhitman** [comment]
Is there an error that should be reported in that instance, instead of omitting the test, should it report an error?

**Comment by daveho** [comment]
Not allowing weak assignments in subexpressions is just a simplifying assumption.  They do evaluate to the result of evaluating the right hand side.  If the input does contain weak assignments that aren't at the top level, the program should report an error.

One thing that I did in the merge was to suppress the run_test.rb script from requiring a specific line number to be reported for errors in inputs with weak assignments, because when reporting a cycle, there could be multiple equally-valid line numbers to report.

Thanks again for the contribution!

**Comment by elwhitman** [comment]
What determines that we should make such an assumption? Is that stipulation a part of the language requirements we were given? This seems not simplifying but rather complicating, but maybe that’s specific to my implementation.  I understood the definition of weak assignments to be that the value of an assignment isn’t known until every weak assignment expression of the program has been considered.

**Comment by elwhitman** [comment]
I have mistakenly overlooked that sub-expression containing weak assignments are forbidden. It looks like contrib10 should produce an error as well.

**Pull request merged**
